export const characterStory = {
    MAMA: "",
    CARRIER: "While he has a similar shape to Mama, his hat and bag, thoughts, and appearance are much different.",
    RION: "A prince hailing from a kingdom on the precipice of war, Rion is ostracized by his father due to his sickly demeanor and advocation for peace. After being locked in the castle's storeroom, he meets a defective clockwork soldier, Dimos, with whom he quickly forms a close bond. The two make their way to the throne room to demand a stop to the war, only for the king to label Rion a traitor and order him killed. After a narrow escape, Rion and Dimos decide to travel the kingdom together to find a way to put a stop to the war for the sake of his people. Some time later, the pair find themselves on the outskirts of a windswept town. Looking for a place to rest, they make their way through, only to be stopped by men who recognize the boy as royalty. After a quick altercation, the two decide it best to leave the town behind, continuing their journey. Eventually, they find themselves sheltering in a dilapidated church. Rion rests in the back of the chapel, weak from both his disease and hunger, while Dimos searches for food. He is able to find a few apples, but after being offered them, Rion's body is too weak and frail to accept them. Rion soon after succumbs to his illness, Dimos continuing to protect the prince's body even in death. Over a century later, a bounty hunter, Gayle, makes her way to the church on rumors of a clockwork soldier killing anyone who comes near. When she arrives, a rusted—but still functional—Dimos protecting Rion's corpse remains. The two fight, only for the soldier to be finally struck down. Gayle checks his logs and learns of the pair's past, deciding to build a grave to mourn them before moving on.",
    DIMOS: "An automaton created to serve a corrupt kingdom, Dimos is awakened in the castle cellar by the prince, Rion, after being previously labeled defective. The pair quickly bond over similar circumstances, and upon learning of the kingdom's impending war, make their way to the throne room where Rion demands it stopped. They are quickly dismissed and ordered to be killed for treason, but are somehow able to narrowly escape. Taking Rion as his new charge, Dimos promises to protect the prince, and they begin traveling across the kingdom to spread antiwar ideals. Some time later, Rion and Dimos find themselves upon a windswept town. Looking for a place to rest, they make their way through, only to be stopped by men who recognize the boy as royalty. After a quick altercation, the two decide it best to leave the town behind, continuing their journey. Eventually, they find themselves sheltering in a dilapidated church. Dimos searches for food while Rion rests in the back of the chapel, weak from both long term disease and hunger. He is able to find a few apples, but after being offered them, Rion's body is too weak and frail to accept them. Rion soon after succumbs to his illness, Dimos continuing to protect the prince's body even in death. Over a century later, a bounty hunter, Gayle, makes her way to the church on rumors of a clockwork soldier killing anyone who comes near. When she arrives, a rusted—but still functional—Dimos protecting Rion's corpse remains. The two fight, only for the soldier to be finally struck down. Gayle checks his logs and learns of the pair's past, deciding to build a grave to mourn them before moving on.",
    AKEHA: "An assassin from an infamously renowned family, Akeha shows no emotion carrying out missions assigned to her by her master. Duty set in stone before she was born, she faced grueling training as a child that molded her into the perfect killer. Her newest mission—killing an heir to an enemy territory from the safety of their own castle—is nothing new in her line of work. Easily taking down the guards in her way, she comes across her target, but soon realizes the heir is not a boy, but a girl. The girl resents her position as a puppet under her father, and wishes her house would fall. Akeha contemplates the girls position, finding it similar to her own, and decides to not carry out the assassination. She grants the girl's wish by eliminating all soldiers in the vicinity—receiving a fatal wound in the process—then seemingly dies without regrets.",
    ARGO: "An adventurer who lives only for the rush of going on perilous journeys, Argo spends his days climbing the tallest of mountains and exploring the harshest of environments. His journeying leads him to another such peak, one where no man is said to have ever reached the summit—and while the mountain itself seems to deny him passage, he pushes on. A blizzard soon sets in over the mountain, and Argo is forced to seek shelter in a cave. He recalls a letter and charm in his pocket, given to him by his daughter, which gives him a renewed strength to continue. Halfway up the mountain, he encounters a lake with a corpse along the shore. He finds a note, and in shaky handwriting it relays the corpse's regrets about leaving his family behind to attempt the climb. Argo reaches the final cliff before the peak, and after a perilous ascent he reaches the top. Despite the rumors of no one reaching the summit, he finds a ruined shrine waiting for him. He steps inside, and to his surprise he sees his wife—who questions him about why he would leave his family with a baby on the way. The man rubs his eyes, seeing then the corpse of a pregnant woman holding a familiar charm, and decides to quickly return home to his family. In a snowy forest, a pregnant woman and her daughter await the return of her husband in the comfort of their home. They talk of what they'll do when he gets back, when suddenly the woman clutches her stomach in pain—her baby is ready to be born. Argo awakens below the final cliff before the peak, realizing that he never made it to the top—the shrine was only a final dream he imagined as he fell. He feels for his daughter's charm in his pocket, and with its warmth he closes his eyes.",
    FRENRIZE: "A young woman hailing from a lush and verdant land, Gayle spends her days living and hunting with her younger sister. After an incident with a wild beast, the sisters notice a nearby village being razed. Asking her sister to stay put, Gayle goes to investigate, finding the town a slaughterhouse. Despite her instructions, Gayle's sister arrives and the two attempt to flee when surrounded by kingdom soldiers. Unsuccessful, they are both captured and 'sorted', experimented on and tortured. Some time later, Gayle wakes in a prison with her hair turned stark white and left arm and leg replaced with prosthetics. She escapes after an altercation with a guard, who gleefully states she is now a 'failed killing machine.' Frantically searching for her sister, Gayle finds her on a bloodied battlefield being cut down by an enemy soldier. She blacks out, eventually coming to with bloodied chunks of bodies surrounding them. She gently embraces her sibling before swearing to a life of revenge. Some time in the future, Gayle takes up the job of a bounty hunter and scouts a village saloon for intel on a nearby clockwork soldier. Finding him in an abandoned church, she takes him down, then learns of his past with the corpse he was protecting. She constructs a grave to mourn the pair, then quickly moves on.",
    PRISONER: "An imprisoned soldier from a future where monstrous Flowers threaten human extinction, 063y and his wife, F66x, are forced by the government to fight in the military. Long ago they lived a mundane family life with their son, but it was quickly taken away with the child's death when the Flowers attacked. The prisoner's lives are meticulously controlled; they are told when to eat and have no way of escaping due to their clothing allowing them to be directly controlled. During one of his scheduled mealtimes, 063y hears a familiar alarm—one signifying the arrival of the Flowers. Rushed into battle with his wife and fellow soldiers, they face off against an especially powerful enemy. With everyone defeated except for the pair, they move to flee when suddenly reinforcements arrive and turn the tide of the fight. While celebrating, 063y and F66x are dumbstruck as their allies suddenly turn and begin throwing themselves off a nearby cliff. Their commander appears, explaining that it was an order to jump, and the fact that the two didn't meant they were defective and were to be disposed of. F66x is stabbed, and before her husband can meet the same fate, she shoves him off the cliff where he survives by landing on the broken bodies of his comrades. Some time later, F66x awakens in a ruin, her last memory being that of being stabbed and pushing 063y. She wanders for a while before coming across fellow soldiers, including her husband, and the couple return to a hideout where fellow escaped prisoners plot a large-scale rescue attempt. Putting this plan into motion, they eventually sneak back into the government facility with the goal of winning over their old allies. While searching for escape routes, 063y and F66x are confronted again by their former commander. He explains to them that humanity is actually extinct, and that the prisoners are all clones implanted with false memories that motivate them to fight. F66x is forced by her programming to attempt to kill her husband, but she resists until the end—the end of both the experiment, and her life.",
    WIFE: "An imprisoned soldier from a future where monstrous Flowers threaten human extinction, F66x and her husband, 063y, are forced by the government to fight in the military. Long ago they lived a mundane family life with their son, but it was quickly taken away with the child's death when the Flowers attacked. The prisoner's lives are meticulously managed; they are told when to eat and have no way of escaping due to their clothing allowing them to be directly controlled. One day the couple are rushed into battle with their fellow soldiers and face off against an especially powerful Flower. With everyone defeated except for the pair, they move to flee when suddenly reinforcements arrive and turn the tide of the fight. While celebrating, F66x and 063y are dumbstruck as their allies suddenly turn and begin throwing themselves off a nearby cliff. Their commander appears, explaining that it was an order to jump, and the fact that the two didn't meant they were defective and were to be disposed of. F66x is stabbed, and before her husband can meet the same fate, she shoves him off the cliff where he survives by landing on the broken bodies of his comrades. Some time later, F66x awakens in a ruin, her last memory being that of being stabbed and pushing 063y. She wanders for a while before coming across fellow soldiers, including her husband, and the couple return to a hideout where fellow escaped prisoners plot a large-scale rescue attempt. Putting this plan into motion, they eventually sneak back into the government facility with the goal of winning over their old allies. While searching for escape routes, F66x and 063y are confronted again by their former commander. He explains to them that humanity is actually extinct, and that the prisoners are all clones implanted with false memories that motivate them to fight. F66x is forced by her programming to attempt to kill her husband, but she resists until the end—the end of both the experiment, and her life.",
    LARS: "Молодой солдат Ларс, присоединившийся к армии лишь с одной целью – мстить за убийство своих родителей, оказывается под командованием 'трусливого' капитана в бесконечной войне. Он нагл и непослушен, бросается в бой, не обращая внимания на приказы или свою собственную безопасность. Узнав о миссии, где может присутствовать объект его мести, Ларс отправляется во вражеский лагерь один, несмотря на приказы капитана. Он находит того, кого искал, и быстро убивает его, но умирающий мужчина раскрывает правду о прошлом Ларса: его похитили в детстве и воспитали другие 'родители' в рамках схемы похищения младенцев. Его настоящий отец лежит перед ним, убитый собственным сыном, которого он пытался спасти много лет назад. Опасаясь за его безопасность, капитан Ларса, Гриф, изменяет миссию, чтобы не только уничтожить врага, но и осуществить спасение Ларса. Он находит труп вражеского капитана со знакомым мечом, зная, что молодой солдат не мог уйти далеко. Он находит мальчика – раненого, но живого – и относит его в безопасное место. После последнего столкновения с врагом Гриф обращается к Ларсу и говорит ему, что рад, что он выжил.",
    GRIFF: "",
    NOELLE: "",
    FIO: "A girl with a cheery demeanor despite her circumstances, Fio is described as being from a small town in a faraway country. Her parents often fought because of her father losing his job, due to the country's strict rules on social class and mobility. Her and her family were considered 'Goat People,' a class below Commoners created by the country's Nobles to suppress dissent. The Goat People were often ridiculed, harassed, and abused, as well as forced to wear collars and manacles to show their status. During this time Fio also suffers from recurring nightmares, finding herself in The Cage and meeting Levania. The two make an agreement—in exchange for Levania eating her dreams and getting rid of her nightmares, Levania can become human. Fio's father is killed when he attempts to get back his job in the town's barracks. Devastated by this, Fio returns to her mother, only to discover that she was having an affair and plans to leave. Alone, Fio slowly goes hungry and laments on how no one will care for her because she is a Goat—eventually being forced to leave her home behind.",
    LEVANIA: "A strange monster roaming a strange land, Levania is a Dream Eater who's only desire is to consume human dreams. There are many other Dream Eaters, all driven by a common instinctual desire to become human. Not much is known about Levania past, or the origins of the Dream Eaters. When meeting Fio he is initially cold, not interested in her other than the dreams she provides. Over time they form a bond, Levania eventually learning to care for her well being and happiness, and he vows to become her friend when he is able to become human.",
    PAPA: "Papa has the appearance of a floating, ghostlike being—a white sheet with black holes for eyes and two extendable black arms.",
    DARK_MAMA: "Mama has the appearance of a floating, ghostlike being—a black sheet with white holes for eyes and two extendable black arms. Babe is a much smaller, similar being who rides in her apron.",
    SARAFA: "",
    SARYU: "",
    TENH: "10H has the appearance of a young woman with shoulder length white hair and fair skin. She wears a standard YoRHa uniform consisting of a black dress, blindfold, and thigh high black boots.",
    YUDIL: "",
    MARIE: "",
    YURIE: "",
    YUZUKI: "He is an ordinary high school student that was suddenly transported into The Cage. He cares deeply for his mother and wishes to reunite with her.",
    HINA: "She is a well-regarded honor student that was suddenly transported into The Cage. She cares deeply for her father and wishes to reunite with him.",
    PRIYET: "",
    POD: ""
};

export const modalText = {
    OLDBOY: "В Клетке герои встречают старика. Он рассказывает, что уже очень долгое время ждёт свою маму и просит посадить его обратно в историю, как это было с чёрным монстром. Увы, Мама ничем не может ему помочь. По её словам он был изгнан из истории. Старик явно знал девочку и чёрного монстра и разговаривал словно ребёнок."
}